### ISSUE TITLE
QoD Provider Implementation proposal - From Spry Fox Networks

### ISSUE THREAD

**Issue by SfnUser** [camaraproject/QualityOnDemand#107]
Hi @hdamker 

We, at Spry Fox Networks, would like to contribute to this project by publishing our QoD API implementation. Ours is based on the Go programming language and we believe it would add value for the Camara project target audience. Could you please allocate a `Provider Implementation' repository for us?

Thanks.

**Comment by SfnUser** [comment]
Slides presented in the QoD Call - 27th Jan 2023 - [SFN_QoD_Service_v1.pptx](https://github.com/camaraproject/QualityOnDemand/files/10519348/SFN_QoD_Service_v1.pptx)

**Comment by hdamker** [comment]
Repo https://github.com/camaraproject/QualityOnDemand_PI3 created.
