### ISSUE TITLE
Is enum the best choice for qos_profile ?

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/QualityOnDemand#11]
What if a client needs a QoS profile with LOW_LATENCY and THROUGHPUT_L?
To be able to compose these profiles, we would need to add an enum key that represents this combination and also a new key for all other relevant ones.
Instead, we could associate each profile with values ​​based on the power of two (1, 2, 4, 8, 16...) and compose them via an OR operation. What do you think of this?

**Comment by Marcin-Jarzab** [comment]
Agreed to close and agree on current solution during the meeting : 04.22.2022.
