### ISSUE TITLE
Add documentation into API definition for release v0.9.0

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#144]
**Problem description**

Documentation is not in sync with the API definition (some PRs changed the API documentation in parallel, some not).

**Expected action**

Add documentation to API definition as discussed in https://github.com/camaraproject/WorkingGroups/issues/164

**Additional context**

Agreement is that CAMARA documentation should be embedded within the OAS definition, and not separate. This reduces the effort required in maintaining documentation.

**Comment by ShutingQing** [comment]
@jlurien hi jose, have u started working on this? if not, i can help on this.
