### ISSUE TITLE
Add linting GitHub actions

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/QualityOnDemand#158]
**Problem description**
The validity of the swagger and markdown documents must be manually validated.

**Expected action**
Using GitHub actions, linting can automation be run on all commits to ensure that formatting is always followed.

This action can work for OpenAPI
https://github.com/marketplace/actions/swagger-editor-validator

Other options are available for Markdown

**Additional context**
We could pilot linting in this subproject and then suggest it as a part of the commonalities to use the same linters with a standard configuration.

**Comment by eric-murray** [comment]
Agreed at 11th August meeting for Randy to implement initial linting on v0.10.0-wip, looking to "prettify" code. Randy believes he has sufficient access rights to do this.
