### ISSUE TITLE
QoD API clarifying ques

### ISSUE THREAD

**Issue by SyeddR** [camaraproject/QualityOnDemand#22]
Hello team, we would like to understand reasons behinds few of the parameters in QoD API
1. Are ueAddr and asAddr subnet range and not an individual IP address? What is the reason behind subnet range?
2. uePorts and asPorts are not singular. It will become complicated to create QoS flows for each of ueAddr/uePorts+asAddr/asPorts combination.
3. Why do we have Protocol In and Protocol Out? Shouldn't protocol be the same in both inbound and outbound flow?
4.  Is notificationAuthToken intended to be a permanent token? would'nt it create a security issue?

Appreciate if someone can help provide answers to above ques

**Comment by shilpa-padgaonkar** [comment]
@SyeddR : Points 1,2 and 3 are either covered in the ongoing API documentation review comments or are part of #13 
Point4 is a part of DT's internal backlog for one of the upcoming releases and this new issue is created to track it in Camara [#31](https://github.com/camaraproject/QualityOnDemand/issues/31)

**Comment by hdamker** [comment]
Covered by #13 and #31
