### ISSUE TITLE
Consistent usage of notificationUri vs notificationUrl

### ISSUE THREAD

**Issue by palmerabollo** [camaraproject/QualityOnDemand#23]
In https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-throughput.yaml#L41= a parameter is called `notificationUrl`. In https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-throughput.yaml#L206= it is called `notificationUri`. They should use the same name. The same applies to qos-stable-latency.yaml.

**Comment by hdamker** [comment]
Would be addressed by DT in PR.

**Comment by maxl2287** [comment]
can be closed as an outdated version. Issue #88 can be used instead

**Comment by hdamker** [comment]
Superseded by #88
