### ISSUE TITLE
Remove mobile from QoD scope

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/QualityOnDemand#238]
**Problem description**
The current [scope](https://github.com/camaraproject/QualityOnDemand/blob/1ebca6f7ae9eb37bcbc627007f548c1f5a50f472/README.md?plain=1#L14) limits the API to `set quality for a mobile connection`

This contradicts the commonalities [documentation](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#25-reduce-telco-specific-terminology-in-api-definitions) to not use telecommunications specific terms. 

The documentation in the [API definition](https://github.com/camaraproject/QualityOnDemand/blob/1ebca6f7ae9eb37bcbc627007f548c1f5a50f472/code/API_definitions/qod-api.yaml#L5) also conaties the mobile specific contents.

> The Quality-On-Demand (QoD) API provides programmable interface for developers and other users (capabilities consumers) to request stable latency or throughput managed by Telco networks without the necessity to have an in-depth knowledge of the 4G/5G system or the overall complexity of the Telecom Systems.

**Expected action**

`set quality for an access network connection` or something similar that would apply to mobile and wireline networks.

Update the documentation in the API definition to be consistent with the wording.
 
**Additional context**

**Comment by hdamker** [comment]
Fully agree here that we should change. The changes done within the [Glossary](https://github.com/camaraproject/Commonalities/blob/main/documentation/Glossary.md) (see https://github.com/camaraproject/Commonalities/pull/40) "to be inclusive beyond mobile network" could be here helpful hints.

As this will affect only documentation, my proposal is to do it after the release candidate and before the release of v0.10.0.

**Comment by RandyLevensalor** [comment]
> I don't think that "mobile" is a telecommunications specific term, or more specific than "access network connection". Point here is whether this API is intended for just mobile connections or also for wireline connections. And in the later case, how is this differentiated from HomeDevices QoD scope.

@jlurien My understanding is that the `HomeDevices QoD scope` is limited to inside the customer premises.  When we defined the packetDelayBudget, we attempted to clarify the scope of this API.

```
between the customer's device and the gateway from the operator's network to other networks
```

While we ended up not include the definition of the customer's device in this definition, in the context of the discussion it was the UE for a mobile device and the residential gateway for wireline networks (FN-RG or 5G-RG in some of the 3GPP specs).

I wholeheartedly agree that we should ensure that we are not overlapping with the scope of the HomeDevice QoD api.  Though it would be nice to have an end-to-end QoD API, but that's a topic for another day.

**Comment by hdamker** [comment]
The scope of https://github.com/camaraproject/HomeDevicesQoD is only for the connection from home router to the device within the user's home network. From the [YAML](https://github.com/camaraproject/HomeDevicesQoD/blob/release-0.2.0/code/API_definitions/home_devices_qod.yaml) there:

 ```
    - **NOTE: The scope of the API is as follows**:
      - QoS treatment is applied to a target user device **only within the user's home network** (i.e., between the device and the home router)
      - QoS treatment **only applies to downstream IP traffic** (i.e., from the home router to the target device)
      - QoS treatment **only applies to home devices using WiFi access** (i.e., home router WiFi interface)
 ```

**Comment by hdamker** [comment]
As agreed within the QoD Calls on March 8th and 22nd I created https://github.com/camaraproject/WorkingGroups/issues/402 within the API Backlog Group to inform the working group (and via them the OGW Product Team) about the scope change.

Please have a look if that fits for you @jlurien @jgarciahospital @RandyLevensalor @eric-murray ... happy to update the issue if needed.
