### ISSUE TITLE
Align securitySchemes and security of QOD API spec with IdentityAndConsentManagement

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#244]
**Problem description**
QoD API need to be aligned with the upcoming released version of documents in https://github.com/camaraproject/IdentityAndConsentManagement

**Possible evolution**
Adapt securitySchemes as defined in https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md when it is released (dependent on at least issue camaraproject/IdentityAndConsentManagement/issues/57 and related PR camaraproject/IdentityAndConsentManagement/pull/93).

**Alternative solution**

**Additional context**
For all or some QoD API endpoints `client_credentials` might be an allowed grant type if certain prerequisites are given.

**Comment by hdamker** [comment]
v0.10.0 is already in rc2 and therefore out of the door.

**Comment by jlurien** [comment]
> v0.10.0 is already in rc2 and therefore out of the door. We marked this issue as "enhancement" for the next release. For applying scopes which allow the "wildcard" scope we might need also to think about splitting sessions and profiles in two APIs.

Splitting the API may have all sense. BTW, we are facing some new use cases where QoS profiles may be used by other APIs as well, so that would easy reusing this functionality.

**Comment by hdamker** [comment]
Agreement within QoD Call Feb 9th: the split of QosSessions and QosProfiles to be done first (#265).
