### ISSUE TITLE
Update and enhance test definition file for QOD API

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#245]
**Problem description**

Current [QoD_API_Test.feature](https://github.com/camaraproject/QualityOnDemand/blob/main/code/Test_definitions/QoD_API_Test.feature) should cover the mandatory functionality of the QoD API

**Possible evolution**

Update current .feature file and enhance with additional test cases

**Alternative solution**

**Additional context**

**Comment by jlurien** [comment]
To be aligned with ongoing discussion in Commonalities: https://github.com/camaraproject/Commonalities/issues/94

**Comment by hdamker** [comment]
> To be aligned with ongoing discussion in Commonalities: [camaraproject/Commonalities#94](https://github.com/camaraproject/Commonalities/issues/94)

The [API-Testing-Guidelines.md](https://github.com/camaraproject/Commonalities/pull/117) are in the meantime merged within Commonalities and will get released with Commonalities v0.3.
