### ISSUE TITLE
Duration in QosProfile and SessionInfo

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#249]
**Problem description**
In the latest definition (v0.10.0-rc), we have the option to provide a duration while creating the session and there, the maximum duration of a session is limited to 86400s (1d).
We also have discovery of QoSProfiles by mean of GET /qos-profiles, and there we return per QoSProfile a minDuration and maxDuration, that is no limited. We potentially may allow sessions for up to <Int32> days.

There is a lack of consistency between both endpints.

**Possible evolution**

It makes sense to remove the explicit limitation of duration in sessionInfo, and rely on the discovery of QoSProfiles to let the client know about the allowed limits. The same schema for Duration can be aplied in both.

**Comment by hdamker** [comment]
With last QoD call we have discussed to keep the limit for duration in sessionInfo within v0.10.0 and add a note for the maxDuration parameter within QoSProfile that within v0.10.0 it shouldn't exceed of 86400 seconds/1 day.

The discussion if we should remove the explicit limitation for duration in sessionInfo will be done for the next release, as well as the alignment of the schema for duration.

**Comment by hdamker** [comment]
Removing 'v0.10.0' as the part for this release is temporarily fixed with #256

**Comment by hdamker** [comment]
Fixed with #296
