### ISSUE TITLE
Duration in QoS Session and QoS Profile

### ISSUE THREAD

**Issue by gauravn00b** [camaraproject/QualityOnDemand#266]
**Problem description**
What is the co-relation between Duration in QoS Session and QoS Profile?

**Expected action**
Exact behavior should be mentioned, if either of two does not match.

**Additional context**
There is no clarity mentioned in documentation except it should not exceed 24 hours. However, there is no clarity if both does not match. for eg, if someone provide minduration as 3600 seconds in profile and provide duration as 1800 seconds in session creation, what should be the behaviour here? Or we should remove duration from session creation and rely only on profiles, as recommended in #249 as well

**Comment by hdamker** [comment]
@gauravn00b the `duration` requested within `createSession` is the session duration the API consumer wants to have for the session. It has to be between `minDuration` and `maxDuration` as defined within the qosProfile. These limits are defined by the service provider but they are only defining the lower (e.g. 10 seconds) and upper limit (e.g. 24 hours) but not the actual duration of a session. 

The behaviour in cases where the requested `duration` is outside the range of `minDuration` and `maxDuration` we discussed in https://github.com/camaraproject/QualityOnDemand/issues/247 and introduced the error example `DurationOutOfRangeForQoSProfile` (see https://github.com/camaraproject/QualityOnDemand/pull/259).

If you have a proposal to describe the behavior better within the documentation feel free to open a PR.

#249 is about getting rid of the 24 hour limit within createSession (as we have now `maxDuration` in the `qosProfile` for that), and make the type of the values consistent. But `duration` will stay as parameter in createSession.

**Comment by hdamker** [comment]
Fixed in #296
