### ISSUE TITLE
Polling for `statusInfo` in GET /sessions/{sessionId} not possible

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#267]
**Problem description**

In QoD v0.10.0, it is explained that clients which are polling, because they have not configured a webhook, can poll for qosStatus and `statusInfo`.

>  NOTE: in case of a `QOS_STATUS_CHANGED` event with `qosStatus` as `UNAVAILABLE` and `statusInfo` as `NETWORK_TERMINATED` the resources of the QoS session
        are not directly released, but will get deleted automatically at earliest 360 seconds after the event.
        This behavior allows clients which are not receiving notification events but are polling to get the session information with
        the `qosStatus` `UNAVAILABLE` and `statusInfo` `NETWORK_TERMINATED`.

How should the clients poll for `statusInfo` since this information is only available as part of the CloudEvent?

**Expected behavior**
Remove this `statusInfo` from this note.

**Alternative solution**
Add the `statusInfo` to the GET /sessions/{sessionId} - response.

**Additional context**

`statusInfo` is currently only part of the EventQosChangedEvent

```yaml
    EventQosStatusChanged:
      allOf:
        - $ref: "#/components/schemas/CloudEvent"
        - type: object
          properties:
            data:
              type: object
              description: Event details depending on the event type
              required:
                - sessionId
                - qosStatus
              properties:
                sessionId:
                  $ref: "#/components/schemas/SessionId"
                qosStatus:
                  $ref: "#/components/schemas/EventQosStatus"
                statusInfo:
                  $ref: "#/components/schemas/StatusInfo"
          required:
            - data
```

`statusInfo` is not part of SessionInfo (response-model for GET and POST /sessions)

```yaml
SessionInfo:
      description: Session related information.
      allOf:
        - $ref: "#/components/schemas/CreateSession"
        - type: object
          properties:
            sessionId:
              $ref: "#/components/schemas/SessionId"
            startedAt:
              type: integer
              example: 1639479600
              description: Timestamp of session start in seconds since Unix epoch
              format: int64
            expiresAt:
              type: integer
              example: 1639566000
              description: Timestamp of session expiration if the session was not deleted, in seconds since Unix epoch
              format: int64
            qosStatus:
              $ref: "#/components/schemas/QosStatus"
            messages:
              type: array
              items:
                $ref: "#/components/schemas/Message"
          required:
            - sessionId
            - duration
            - startedAt
            - expiresAt
            - qosStatus
```

**Comment by jlurien** [comment]
Agree with the problem. IMO, we should add `statusInfo` to `SessionInfo` schema
