### ISSUE TITLE
X-Correlator required within OAS definition of QualityOnDemand API

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#271]
**Problem description**

Release v0.3.0 of commonalities requires in chapter 9 of API-design-guidelines.md to include the X-Correlator header parameter as mandatory within the OAS specification. 

**Expected behavior**

The header parameter is added as intended within the YAML file. 

**Alternative solution**

none

**Additional context**

**Comment by jlurien** [comment]
Related to this is clarification being discussed at https://github.com/camaraproject/Commonalities/issues/164
