### ISSUE TITLE
Question on the anyOf in DeviceIpv4Addr

### ISSUE THREAD

**Issue by jimbobbennett** [camaraproject/QualityOnDemand#276]
**Problem description**

I'm looking at the `DeviceIpv4Addr` schema, and I'm unsure about the `anyOf` and if it is valid OpenAPI:

(trimmed description/examples for brevity)

```yaml
DeviceIpv4Addr:
  type: object
  properties:
    publicAddress:
      $ref: "#/components/schemas/SingleIpv4Addr"
    privateAddress:
      $ref: "#/components/schemas/SingleIpv4Addr"
    publicPort:
      $ref: "#/components/schemas/Port"
  anyOf:
    - required: [publicAddress, privateAddress]
    - required: [publicAddress, publicPort]
```

My understanding is that the intention of this `anyOf` is to enforce that _either_ `publicAddress` and `privateAddress` are set, _or_ `publicAddress` and `publicPort`.

Whilst this passes swagger validation using the action in this repo, when I view this in the swagger editor, it doesn't render this correctly:

<img width="908" alt="image" src="https://github.com/camaraproject/QualityOnDemand/assets/1710385/f6a2568f-9fe2-484f-a208-62a09baf2ab6">

Notice the `anyOf` is empty.

This suggests that it is not valid OpenAPI.

**Expected behavior**

This should be valid OpenAPI and be able to be interpreted by standard tools

**Alternative solution**

This is what I feel is more correct (though not as nice to read):

```yaml
DeviceIpv4Addr:
  anyOf:
    - allOf:
      - $ref: "#/components/schemas/DeviceIpv4AddrObject"
      - required: [publicAddress, privateAddress]
    - allOf:
      - $ref: "#/components/schemas/DeviceIpv4AddrObject"
      - required: [publicAddress, publicPort]

DeviceIpv4AddrObject:
  type: object
  properties:
    publicAddress:
      $ref: "#/components/schemas/SingleIpv4Addr"
    privateAddress:
      $ref: "#/components/schemas/SingleIpv4Addr"
    publicPort:
      $ref: "#/components/schemas/Port"
```

This comes out in the swagger editor like this:

<img width="919" alt="image" src="https://github.com/camaraproject/QualityOnDemand/assets/1710385/db2a001c-a244-4e92-a8c4-fa8f19d046fc">

The `anyOf` now lists everything correctly, and has red asterisks to show the required fields.

I'd appreciate your thoughts on this to help my understanding.

**Comment by jimbobbennett** [comment]
In addition - when I run the spectral validation action that is configured for manual workflow, I also see a warning about this schema:

```
  977:20     hint  camara-discriminator-use        Ensure that API definition YAML files with oneOf or anyOf sections include a discriminator object for serialization, deserialization, and validation.  components.schemas.DeviceIpv4Addr
```

**Comment by jlurien** [comment]
Hi,

This is not a very common use of anyOf, but I wouldn't assume that lack of support from Swagger editor means that spec is not compliant with OAS. ,You can check that Redocly understands it, and it currently shows something very similar to what Swagger editor shows after your alternative version:

![image](https://github.com/camaraproject/QualityOnDemand/assets/2392199/0dce1701-20da-476d-843b-b37485df5325)
![image](https://github.com/camaraproject/QualityOnDemand/assets/2392199/d3f35228-b4c7-46aa-8507-89e34d7b0c7a)

Regarding the linter warning, I think that it does not apply to this case as there is no discriminator property to use.

**Comment by patrice-conil** [comment]
Hi @jimbobbennett ,@jlurien, 
I've tried both versions with openapi-generator (tagetting jaxrs-spec).
Current version that uses anyOf only in required section is usable (constraints are not embedded in generated DeviceIpv4Addr but model is consistent)
Jim's proposed version that uses a combination of anyOf and allOf produces an unusable model (No fields present in DeviceIpv4Addr)... probably due to the lack of a discriminator in the spec.
So my preference is to continue with actual definition.

**Comment by hdamker** [comment]
Based on comment and the discussion within QoD Call on April 19th added "won't fix". Will be closed on April 26th if there are no further comments.
