### ISSUE TITLE
Clarification of session creation and startedAt

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#280]
**Problem description**
Current documentation is ambiguous about when the session starts. The session is always created synchronously, returning 201 with SessionInfo, and `startedAt` (Timestamp of session start) is required even if `qosStatus` = `REQUESTED`, so the value must be *now* the createSession response time as the time when `qosStatus` becomes `AVAILABLE` is unknown.

But we also describe:

> If the qosStatus in the API response is REQUESTED, the client will receive either
> * a `QOS_STATUS_CHANGED` event notification with `qosStatus` as `AVAILABLE` after the network notifies that it has **created the requested session**

So when is the session considered to be created and when is the session considered started? 
* Should `startedAt` refer to the moment when `qosStatus` is `AVAILABLE`? and then it cannot be required in SessionInfo
* Should `startedAt` refer to the moment when the session is created, even if even if `qosStatus` = `REQUESTED`? and then `QOS_STATUS_CHANGED` event with `qosStatus` as `AVAILABLE` cannot mean that network has created the requested session.

In the end we need to clarify if duration starts when SessionInfo is created (even if `qosStatus` = `REQUESTED`)  or when `qosStatus` =. `AVAILABLE`

**Expected action**

Clarify concepts. Eventually define a new property `requestedAt` to mark the SessionInfo creation time and make `startedAt` and `expiresAt` as optional, to be filled when qosStatus is available.

**Comment by hdamker** [comment]
Should we make the timespan for "REQUESTED" limited to some amount (as it is expected to be in range few seconds) => new issue.

**Comment by hdamker** [comment]
Fixed in #280
