### ISSUE TITLE
startedAt y expiredAt do not follow date-time format

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#281]
**Problem description**
Currently the properties in SesssionInfo `startedAt` and `expiresAt` are defined as "in seconds since Unix epoch", but this is very excepcional in CAMARA as all other time properties have format date-time, following RFC 3339.

Commonalities do not explicitly mandate to follow date-time format for time values, only to add reference to RFC 3339 if used, but it may require some more explicit guideline for this.

**Expected behavior**

Is this intentional or should we adopt date-time as well, which is more friendly for humans.

**Comment by eric-murray** [comment]
Happy to move to `date-time` format, but would like seconds to continue to be constrained to an integer, as fractional seconds would be excessive precision for this use case.

**Comment by hdamker** [comment]
QoD Call on April 19th: Agreed to be done in scope of v0.11.0.

**Comment by tanjadegroot** [comment]
the common data types from commonalities has StartDate and EndDate types of type date-time, so I think the both name and type of the schema(s) in qod should be aligned to the common ones. Other types may also need to be checked. 
btw the DeviceStatus has a similar schema called "startsAt" that also should be aligned to common schema.

**Comment by hdamker** [comment]
Fixed in #296
