### ISSUE TITLE
Current CI expects certain fixed name for yaml spec

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#290]
**Problem description**
The current CI reports an error for PR #289 due to expect the old name of the yaml file:

 ```
Run `npm audit` for details.
Run cd /home/runner/work/_actions/char0n/swagger-editor-validate/v1.3.2 && SWAGGER_EDITOR_URL=https://editor.swagger.io/ DEFINITION_FILE=code/API_definitions/qod-api.yaml IGNORE_ERROR= node src/index.js
Error: Error while validating in Swagger Editor
Error: Error: ENOENT: no such file or directory, open '/home/runner/work/QualityOnDemand/QualityOnDemand/code/API_definitions/qod-api.yaml'
Error: Process completed with exit code 1.
```

**Expected action**
Enhance the CI so it runs the validation on every *.yaml file which is located under /code folder

**Comment by jlurien** [comment]
https://github.com/camaraproject/QualityOnDemand/blob/main/.github/workflows/swagger-editor-validator.yml#L19

`definition-file`  expects a filename. We may add one step per filename and edit the file each time the filename is changed or some file is added or removed. Or a more elaborated solution, e,g. https://docs.github.com/es/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by hdamker** [comment]
An alternative solution would to drop this GitHub action completely ... it is not coming from Commonalities, but specific here in the sub project. But I would be fine as long someone is maintaining it.

**Comment by hdamker** [comment]
Decision with QoD meeting May 3rd:

Drop the GitHub action for now, bring only back if we encounter anomalies which are not catched by MegaLinter.
