### ISSUE TITLE
Invalid `MeetingMinutes` - reference in README.md

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#307]
**Problem description**
The following Meeting Minutes reference in the README.md is invalid:
https://wiki.camaraproject.org/display/CAM/Quality+on+Demand+Meeting+Minutes

**Expected action**
Change it to: 
https://wiki.camaraproject.org/display/CAM/QualityOnDemand+2024+Minutes

**Additional context**

**Comment by hdamker** [comment]
My proposal is to change the link to https://wiki.camaraproject.org/x/0AOeAQ, to make it robust against name and year changes.
