### ISSUE TITLE
Purpose of `messages` array in SessionInfo schema is undocumented

### ISSUE THREAD

**Issue by sfnuser** [camaraproject/QualityOnDemand#309]
**Problem description**
`SessionInfo` schema in the spec contains `messages` object. The purpose of this object is undocumented

**Expected behavior**
This array object seems unnecessary and can be removed. If there is an purpose, it needs to be documented for implementation by vendors and use by developers.

**Comment by eric-murray** [comment]
Happy for this to be removed

**Comment by hdamker** [comment]
There were no objections to remove the array object raised within the QoD Call today. 
@sfnuser please create the PR for it as agreed.
@camaraproject/quality-on-demand_maintainers if you are using this array and want to keep it, please describe your use case.
