### ISSUE TITLE
Align error responses for Device Object with v0.4.0 of Design Guidelines

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#316]
**Problem description**

The 0.4.0 release candidate of Commonalities defines in chapter [Error Responses - Device Object](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#62-error-responses---device-object) of Design Guidelines the error responses around Device Object

**Expected behavior**

The error responses should be aligned with the definition in Design Guidelines.

**Alternative solution**

**Additional context**

The resolution of this issue will include the 422 for "DEVICE_NOT_APPLICABLE", therefore the PR should be done together with #315.

**Comment by jlurien** [comment]
We have proposed PRs for the same issue in Device Location, that may serve as an example, such as https://github.com/camaraproject/DeviceLocation/pull/215
