### ISSUE TITLE
Alignment of notification web hook to CloudEvent subscription model

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#332]
**Problem description**

Commonalities 0.4.0 introduced the CloudEvent subscription model with 'sink' and 'sinkCredentials' instead of 'notificationUrl' and 'notificationAuthToken', including the needed schema, within chapter 12.1 of the API Design Guidelines.
quality-on-demand uses implicit subscription for QoS Session and must be aligned for the Fall24 release.

**Expected behavior**

Align quality-on-demand API with the changes introduced by https://github.com/camaraproject/Commonalities/pull/198 ff.
Change org.camaraproject.qod.v0.qos-status-changed -> org.camaraproject.quality-on-demand.v0.qos-status-changed 

**Alternative solution**

**Additional context**

#299 has to be adapted accordingly

**Comment by jlurien** [comment]
@hdamker I have just updated QoD provisioning to the new formar (sink + sinkCredential), adjusting also some descriptions in info. I think it can be replicated to quality-on-demand as it is.
