### ISSUE TITLE
Update reference to the QoS Profiles API

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#333]
**Problem description**
Currently the link to the QoS Profiles is marked as _TBC_

```yaml
 * **QoS profiles and QoS profile labels**:
    Latency, throughput or priority requirements of the application mapped to relevant QoS profile values. The set of QoS Profiles that an operator is offering can be retrieved by means of the [QoS Profile API](link TBC).

```

**Expected behavior**
```yaml
 * **QoS profiles and QoS profile labels**:
    Latency, throughput or priority requirements of the application mapped to relevant QoS profile values. The set of QoS Profiles that an operator is offering can be retrieved by means of the [QoS Profile API](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-profiles.yaml).

```

**Comment by eric-murray** [comment]
Agree, but need to remember to update for each release tag. Relative links don't work in the YAML.

**Comment by hdamker** [comment]
@maxl2287 thanks for the catch.

As one of the goals of the split was to make the implementation of qos-profiles optional (at least for the current release) and to avoid a link to main, I will propose the following sentence:

`The set of QoS Profiles that are available may be retrieved via the qos-profiles API (cf. https://github.com/camaraproject/QualityOnDemand/) or will be agreed during the onboarding with the service provider.`

WDYT?
