### ISSUE TITLE
Remove reference to protocol in sink description

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#338]
**Problem description**

`sink` description includes a  reference to the "selected protocol" but we are not including the `protocol` property

**Expected behavior**

Remove that reference or indicate explicitly that it must be HTTP:

"The address to which events shall be delivered using the selected protocol." -> "The address to which events shall be delivered." or  "The address to which events shall be delivered, using the "HTTP" protocol."

**Alternative solution**

Add the `protocol` property as in the artifact to be prepared in the future to allow protocols other than HTTP, but this could be done in a future release. In this case it would be better to group all related properties under a new object, e.g. "notifications: { sink, sinkCredential, protocol, etc } and probably it would be good to indicate the model for implicit subscriptions more clearly in the guidelines.

**Additional context**

We may add the description fix to the PR #336, make a separate PR, merge it and then rebranch PR #336, or wait for rc.2

**Comment by jlurien** [comment]
@hdamker for your consideration

**Comment by hdamker** [comment]
@jlurien Within quality-on-demand we had addressed that already in #335. Have done now the alignment of the sink description between quality-on-demand and qod-provisioning within #336 and updated the PR description.

**Comment by hdamker** [comment]
Fixed in #336
