### ISSUE TITLE
Resolving "in" and "out" ambiguity

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/QualityOnDemand#35]
The current API definition uses "in" and "out" to define flow direction (as in "protocolIn" and "protocolOut"), but these are relative terms and hence ambiguous. The UE would view "in" as the downlink and "out" as the uplink, whereas the AS would view "in" as the uplink and "out" as the downlink. And who know what a 3rd party API caller would think.

As UE and AS are explicitly identified in the API, I would suggest to define flow direction in terms of these actors to avoid any possibility of confusion. So "protocolIn" would become "protocolAStoUE" and "protocolOut" would become "protocolUEtoAS". And if the eminently sensible proposal in issue #32 to replace "protocolIn" and "protocolOut" with "protocol" and "direction" parameters is adopted, then the options for "direction" would be "UEtoAS", "AStoUE" and "BOTH".

**Comment by hdamker** [comment]
I fully agree that we need clear parameter names and values for them which are understandable. Closing this issue to focus the discussion in #32.
