### ISSUE TITLE
Specifying asymmetric QoS flows

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/QualityOnDemand#36]
The current API definitions require that the same QoS is applied to both the uplink and downlink, albeit that it can be applied to different protocols. For LOW_LATENCY, this is reasonable, as it is usually the round trip latency that is important. But for the throughput QoS profiles, this means the same throughput level (THROUGHPUT_L, THROUGHPUT_M or THROUGHPUT_S) must be applied to both the uplink and downlink. This imposes an unnecessary expense on the API consumer, who may only require the enhanced throughput in one direction.

To allow asymmetric QoS flows to be specified using the protocolIn and protocolOut parameters, a "NONE" option should be added to the Protocol schema enumerations. If the proposal in Issue #32 to replace "protocolIn" and "protocolOut" with "protocol" and "direction" is adopted, then this issue no longer arises as directional QoS levels can be specified using the relevant "direction" option (AStoUE, UEtoAS or BOTH).

**Comment by shilpa-padgaonkar** [comment]
CAn be closed if PR37 is accepted

**Comment by hdamker** [comment]
PR #37 has not been merged, new issue #51 created for the backlog.

**Comment by hdamker** [comment]
@eric-murray can the issue be closed as superseded?

**Comment by eric-murray** [comment]
Yes, I'll close it. The agreed solution appears to be to introduce "direction" and "protocol" parameters, but this will need to be added to v0.8.0 with a later PR.
