### ISSUE TITLE
For many app use-cases, executing QoD is impossible due to lack of visibility of IP addresses. 

### ISSUE THREAD

**Issue by magnusolden** [camaraproject/QualityOnDemand#373]
**Problem description**
As an app developer (e.g., Web App/Android/iOS) I do not necessarily have access to the IP addresses for the flows I would like to get QoD for. 

For example, many apps outsource real time traffic to hosted WebRTC services. For other apps this management may be handled by a different team run in different threads. Load balancing may change the IPs in a session. 

Personally, we are trying to make SDKs to make it simpler for app to understand the potential impact of QoD and execute it, and we are blind to the specific IP Addresses. If the App is behind a NAT it may be impossible to know the full 5-tuple (e.g., tethering, FWA). 
 
**Possible evolution**
Let the app request the device identifier, which can be hashed for privacy (it is unclear for me if this is possible through https://github.com/camaraproject/IdentityAndConsentManagement, let us know if it is).

Subsequently the app can open a QoD request for just port for the device identifier. Ports are more stable than IPs and will therefore cover more use-cases without simply giving QoD to the entire device

The flow would be:

1. Request (hashed) device identifier (which device am I connected to?)
2. Request QoD with device identifier and dest port

**Comment by magnusolden** [comment]
Hi @eric-murray thanks a lot for your response! The Front End Flow is very much what we were looking for concerning device ID! 

With regards to IP addresses for requesting QoD. From my understanding (and the QoD APIs we've tested), to request QoD you need the specific dest IP address. Is this correct?

There are quite a few use-cases where this is not feasible. A real use-case we are working on: Building an enterprise app that requests QoD for Video Conference apps once active. The Enterprise app has no way of knowing the specific IP addresses that each session is using (knowing the ports are much more feasible). Hence QoD will miss out on the use-case of enterprises ensuring premium connectivity for employees for Video Conference or other real time collaboration tools. 

Another use-case. We've built a Teams plugin that measures QoO (likelihood of perfect outcome), we would also like this discover available QoD APIs help the end-user understand if there is a point of executing QoD. From the plugin, we don't know the IP addresses of the media flow, hence we cannot initiate QoD for it. I also believe this will be a use case for many apps that uses WebRTC services like livekit or whereby.

**Comment by eric-murray** [comment]
To apply an enhanced QoS profile to a given flow, we need to be able to identify that flow. The decision was taken to base this on IP addresses (and ports), as this would applicable to all the underlying networks that are in scope of this API. The assumption was that, for most use cases, either an application on the device or the application server itself would be calling the API, and thus the application server IP addresses would be known.

If I understand your scenario, you have a 3rd party application that is aware there is communication between the device and an application server, but does not know the specific details, but would nonetheless like to apply enhanced QOS to that flow. I see two options here:
- If you knew the server URLs involved, you could resolve these yourself and use the resulting list of IP addresses as the application server IP addresses. If the service redirects to other URLs, you would need to know the full set.
- Alternatively, you could apply the enhanced QoS to all possible application server IP addresses (0.0.0.0/0), which would prioritise the target application, but also everything else that the device is doing. The assumption would have to be that, if the end user is on a video call, they won't also be playing interactive games (though sometimes I wonder).

If neither of these options work, then how would you propose it would work? What do you know about the IP flows that would allow the network operator to identify which one(s) need to be prioritised with an enhanced QoS profile?

**Comment by magnusolden** [comment]
You understand the scenario correctly. Your second option, setting enhanced QoS to all possible application server IP addresses (0.0.0.0/0), combined with devicePorts is exactly what we are looking for! This was basically what I suggested, because I did not realize that we could use (0.0.0.0/0) as a wildcard. Thanks! This will also work with devicePorts? 

That way we can for, for example Teams, set (0.0.0.0/0) devicePorts: 3478, 3479, 3480, 3481. The real time traffic from Teams will get enhanced QoS while we filter almost all other traffic. Most real time collaboration tools uses ports not commonly used by other apps, so this should get us a long way.

**Comment by eric-murray** [comment]
I think it is `applicationServerPorts` that you want to configure, which are the destination ports opened by the application server (e.g. 443).

`devicePorts` refers to the source ports of the end user's device (e.g. smartphone). Although not very well described, these are the "private" (pre-NAT) ports used by the device, which are typically ephemeral. For most scenarios, setting these should not be required.

**Comment by magnusolden** [comment]
Thanks a lot @eric-murray. This is exactly what we were looking for. We will test and report any issues
