### ISSUE TITLE
Impact on Camara on the definition of flowid in NEF API AfSessionWithQosSubscription

### ISSUE THREAD

**Issue by mbsfn** [camaraproject/QualityOnDemand#41]
Currently there is no support for multiple ip flows in the Camara QoD Apis, so when constructing the corresponding NEF AfSessionWithQosSubscription parameters, which include a 'flowId', it is presumed that this will simply be set to something like '1'. However, considering the relevant 3gpp specifications it appears that the 'flowId' is in fact a tuple consisting of 16 bits for 'the media component number' and 16 bits for the 'ip flow number'. This issue is discussed in the attached pdf. If the analysis is correct, then, since media component numbers start from 1, we should in fact encode the 'flowId' as 0x00010001 (decimal 17). This may seem a trivial matter, but it underlying this is the fact that the internal internal southbound 3gpp APIs towards the PCF are highly expectant of ip flows being defined in the style of AF level SDP exchanges which detail media components and ip flows within them. This has implications for the evolution of the Camara APIs if and when they come to support multiple flows. There is an opportunity to inquire 3gpp about the structuring of the 'flowId' parameter (why not break the tuple out explicitly?) and also to inquire why it is that a single QosReference applies to all flows in a AfSessionWithQosSubscription, which is inconsistent with the equivalent southbound PCF API. Any existing insight on these matters within the Camara community would be of interest, prior to making such enquiries.
[AfSessionWithQos.pdf](https://github.com/camaraproject/QualityOnDemand/files/9608697/AfSessionWithQos.pdf).

**Comment by eric-murray** [comment]
@mbsfn 
Hi Mike

I think your queries are better addressed directly to 3GPP. Whilst using the NEF as the backend to fulfil CAMARA APIs such as the QoD API is the reference solution, and hence implicitly recommended, it is not mandated and API providers (i.e. mobile operators) may adopt a different solution, possibly not even a 3GPP standardised solution. Many operators have not even deployed 5G SA networks yet, nevermind the NEF.

But where a mobile operator does use the NEF to fulfil the QoD API request, we will be faced with the same limitations on the T8 interface that you identify in your presentation. If CAMARA does agree to adopt a QoD API that allows multiple flows to be specified with different QoS requirements per flow, that does not mean we would be able to "fast track" the necessary changes to support this in a single request to the T8. Rather, there would be a period of time, possibly considerable, when the operator API gateway would need to make multiple calls to the NEF to fulfil the request, and track the details of each session itself. For anyone with experience of implementing stateful API gateways, this is not an enticing prospect, but it is possible.

If I understand your presentation, you identify the following issues with the current T8:
- Only individual "flows" can be identified by the flowId (an integer) and not separate media components consisting of multiple "flows" (media subcomponents)
- All "flows" requested using the T8 must have the same qosReference
- If CAMARA QoD API providers were to encode the "flowId" as two concatenated 16 bit numbers (first for media component and second for media subcomponent), this would make it easier for the NEF to construct the correct call to the PCF should that be the network element setting the QoS policy for each flow

My comment would be that the T8 interface specification (29.122, slightly updated in 29.522) significantly predates the PCF specification, and so I would expect the T8 to be updated in time, particularly once the NEF becomes more widely deployed and experience in its use gained. The limitation of one qosReference for all flows is widely recognised. Your "workaround" solution allows multiple media components with media subcomponents to be specified without change to the T8, but is essentially proprietary (non-standardised) behaviour that NEF vendors may or may not be willing to support.

I think it more likely that the T8 flow specifier will eventually be updated to support media components and subcomponents if that becomes a significant use case for the NEF. CAMARA members could lobby for this, but it will be the NEF vendors within 3GPP that drive this.

**Comment by hdamker** [comment]
@mbsfn @SfnUser As discussed in todays call: please add more information about the impact/changes you see for the QoD API definition in Camara.

**Comment by mbsfn** [comment]
In preparation for using Camara QOD APIs AFs will likely have negotiated with UEs (using SDP) a set of flows each defined by ‘media component numbers’ and ‘ip flow numbers’ within. We believe that in 5G use cases these are intended to directly match the ‘MedCompN’ and ‘fNum’ parameters used in the PCF Npcf_PolicyAuthorisation Create API, i.e., the PCF is going to need to have matching MedCompN’ and ‘fNum’ values presented to it in order to set up the appropriate PDU Session. 

If the NEF is to be used then these two parameters must necessarily be passed to the NEF. Currently, barring a spec. update, the only way to do this is by encoding both these items into the ‘flowId’ in the AfSessionWithQos Create. We believe that CR should be raised on the NEF AfSessionWithQos API in TS 29.122 to split out the ‘flowId’ into ‘MedComp’ and ‘fNum’ to make the interface clearer, but there is no need for the Camara Qod API to wait for this development: the necessity of separating out  ‘MedCompN’ and ‘fNum’ is already clear, in our view.

A MedCompN value of zero is not applicable for data flows, so it will not be possible for an NEF to work around this by simply setting the ‘fNum’ to the ‘flowid’ supplied in the Camara API and the ‘MedCompN’ to zero. 

Inevitably NEF vendors / 3gpp are going to have to address the weakness in the 29.122 spec with regard to the ‘flowId’ definition but it would also be in Camara's interest to highlight this, to help get integrations working over 5G up and running as soon as possible. 

In short, Camara may as well anticipate this and replace ‘flowId’ with a ‘media component number’ / ‘ip flow number’ tuple.

When it comes to notifications, the PCF supports notifications on a per flow basis, where a flow is defined as a "MedCompN:fNum" tuple. Our interpretation is that the NEF also has to use the "MedCompN & fNum" encoding to derive the Flow impacted.

We cannot see that there is no impact to Camara if the API is intended to be compatible with NEF usage. Both NEF & PCF 3GPP standards imply a Flow to be "MedCompN:FNum" tuple. How is CAMARA is going to address this?

We are pointing out the references to show it is a problem. If it is not believed to be a problem, then we should be able to see an explanation, or ideally a demonstration of the QOD API working with an NEF, showing the population of medCompN towards the PCF and an explanation of where the medCompN value came from.

If Camara anticipate a component or layer between CAMARA API & NEF to do this transformation or some kind of lookup is assumed at some inside the 3gpp NFs to derive the MedCompN value, it would be better to document this because as of today these APIs seem to be intended to allow seamless communication with the NEF, when NEF is the southbound interface.

**Comment by eric-murray** [comment]
The issue of creating multi-modal flows for a given UE is being studied by 3GPP SA2 as part of Work Item 940068 (FS_XRM)
https://www.3gpp.org/dynareport?code=WiVsSpec--940068.htm

Please review the associated documentation to see if this work covers your intended use case.

**Comment by hdamker** [comment]
Will close as discussion as there are no new comments since two months.
