### ISSUE TITLE
Parameter names used in the API spec need to be revisited to make them more developer friendly

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/QualityOnDemand#44]
As we have discussed during the calls, there is need to take a closer look at the parameter names used in the API spec with the objective of making the parameter names more developer friendly such that they can be understood by just going over the spec and would not require them to reference a separate document.

Example:
"asId" can be renamed to "applicationServerEndpoint"

This needs to be looked at high priority as changing the parameter names after initial release will impact backward compatibility.

**Comment by hdamker** [comment]
Fully agree that this has to be addressed before the first release. Just the addition that some of the parameter names are relevant across several APIs (e.g. a better name for "UeID") and should be defined in context of the API Design Guidelines in the Commonalities Working Group.

**Comment by GarethWGSMA** [comment]
In a similar vein, can I ask if we've stipulated in commonalities whether the uri's should be formatted using spinal case, camel case or pascal case etc? I'm wondering as we're producing a suite of 8 API's, that the developers would appreciate consistency - thus it needs setting in the commonalities and not leaving it to the individual working groups.

**Comment by RandyLevensalor** [comment]
Is there any interest in updating these names to be more inclusive of wireline broadband service?

For instance replacing mobile specific terms like UE with something more inclusive.  Such as device, user_devices, cpe, or target_device.

**Comment by GarethWGSMA** [comment]
Hi,

I thought there was guidance in Camara commonalities (or at least should be), about API formatting.

Gareth

**Comment by hdamker** [comment]
Superseded by #90 as requested by Commonalities.
