### ISSUE TITLE
Update of API documentation

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#58]
[QoD_Stable_Bandwidth_API.md](https://github.com/camaraproject/QualityOnDemand/blob/main/documentation/API_documentation/QoD_Stable_Bandwidth_API.md) and [QoD_Stable_Latency_API.md](https://github.com/camaraproject/QualityOnDemand/blob/main/documentation/API_documentation/QoD_Stable_Latency_API.md) need to be consolidated into (new) QoD_API.md and updated according to updated [qod-api.yaml](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qod-api.yaml)

**Comment by ShutingQing** [comment]
Interested in this, but the link is 404 right now. 'QoD_Stable_Bandwidth_API.md'
