### ISSUE TITLE
Add new endpoint in QoD API to request available qos_profiles

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/QualityOnDemand#7]

**Comment by RandyLevensalor** [comment]
> It would be great to have an API to list the available QOS profiles which are available for a specific user and / or device. The list of QOS profiles would include the attributes for each profile.

The query extensions are in issue #147

Go ahead and close this issue

**Comment by hdamker** [comment]
As agreed in call ... remaining functionality in #147
