### ISSUE TITLE
API error in Swagger Editor

### ISSUE THREAD

**Issue by bheuse** [camaraproject/QualityOnDemand#9]
Loading the API into Swagger Editor, having an error :

https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/QualityOnDemand/main/code/API_definitions/qos-stable-latency.yaml

![image](https://user-images.githubusercontent.com/44679967/160857615-f9cb5279-231c-4cec-a1a4-d9abefb08eff.png)

**Comment by T-sm** [comment]
Thank you for noticing. I created a PR #10 correcting the security requirements.

**Comment by T-sm** [comment]
No feedback for the last ten days, since this is a minor bug correction (2 lines in total), I am merging the PR.
I am keeping this issue open this for the next few days should there be any additional comments.

**Comment by T-sm** [comment]
PR with correction has been merged, there are no further comments. I am closing the issue.
