### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#98]
In anticipation of the [versioning guidelines](https://github.com/camaraproject/WorkingGroups/pull/123) from Commonalities there should be a CHANGELOG.md within the project.

Will generate an initial one from the release descriptions of v0.1.0 and v0.8.0.

Going forward a new release could be discussed and agreed by a pull request to the CHANGELOG.md. The merge commit of this pull request will be then tagged as the release (not for v0.8.0 as we are already beyond that point).

**Comment by jlurien** [comment]
I just commented on the PR, but I copy the same here. I'm OK with taking that changelog from releases for the current status of the project, but we should follow the changelog template proposed in commonalities at some point, when the API is mature enough and we have to highlight the relevant changes between versions of the spec.
